import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>High-Speed, Secure & Anonymous VPN Service | ExpressVPN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container-fluid px-0">
        <nav className="navbar navbar-expand-lg bg-light">
          <div className="container">
            <a className="navbar-brand" href="#">
              <img
                src="https://www.expressvpn.com/frtr/assets/images/edsv2/logo/expressvpn-logo-red.svg"
                width="200"
                height="70"
                alt="header_logo"
                className="img-thumbnail border-0 bg-transparent"
              />
            </a>
            <div
              className="collapse navbar-collapse justify-content-center"
              id="navbarSupportedContent"
            >
              <ul className="navbar-nav ms-auto mb-2 mb-lg-0">
                <li className="nav-item dropdown">
                  <a
                    className="nav-link dropdown-toggle text-dark h4 fw-bold"
                    href="#"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    What is a VPN ?
                  </a>
                  <ul className="dropdown-menu">
                    <li>
                      <a className="dropdown-item" href="#">
                        Action
                      </a>
                    </li>
                    <li>
                      <a className="dropdown-item" href="#">
                        Another action
                      </a>
                    </li>
                    <li>
                      <hr className="dropdown-divider" />
                    </li>
                    <li>
                      <a className="dropdown-item" href="#">
                        Something else here
                      </a>
                    </li>
                  </ul>
                </li>
                <li className="nav-item dropdown">
                  <a
                    className="nav-link dropdown-toggle text-dark h4 fw-bold"
                    href="#"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    Products
                  </a>
                  <ul className="dropdown-menu">
                    <li>
                      <a className="dropdown-item" href="#">
                        Action
                      </a>
                    </li>
                    <li>
                      <a className="dropdown-item" href="#">
                        Another action
                      </a>
                    </li>
                    <li>
                      <hr className="dropdown-divider" />
                    </li>
                    <li>
                      <a className="dropdown-item" href="#">
                        Something else here
                      </a>
                    </li>
                  </ul>
                </li>
                <li className="nav-item">
                  <a
                    className="nav-link text-dark h4 fw-bold"
                    href="#"
                    role="button"
                    aria-expanded="false"
                  >
                    Support
                  </a>
                </li>
                <li className="nav-item">
                  <a
                    className="nav-link text-dark h4 fw-bold"
                    href="#"
                    role="button"
                    aria-expanded="false"
                  >
                    Blog
                  </a>
                </li>
                <li className="nav-item">
                  <a
                    className="nav-link text-dark h4 fw-bold"
                    href="#"
                    role="button"
                    aria-expanded="false"
                  >
                    My Account
                  </a>
                </li>
                <li className="nav-item dropdown">
                  <a
                    className="nav-link dropdown-toggle text-dark h4 fw-bold"
                    href="#"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    English
                  </a>
                  <ul className="dropdown-menu">
                    <li>
                      <a className="dropdown-item" href="#">
                        Action
                      </a>
                    </li>
                    <li>
                      <a className="dropdown-item" href="#">
                        Another action
                      </a>
                    </li>
                    <li>
                      <hr className="dropdown-divider" />
                    </li>
                    <li>
                      <a className="dropdown-item" href="#">
                        Something else here
                      </a>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div className="d-flex justify-content-center">
          <div className="position-absolute mt-5 pt-5 text-dark d-flex justify-content-center flex-column text-center">
            <h1 className="main_heading">The VPN that just works</h1>
            <h3 className="my-3">
              Go further with the #1 trusted leader in VPN
            </h3>
            <button className="btn btn-success rounded-pill py-3 fw-bold text-white my-3 w-25 align-self-center">
              Get ExpressVPN
            </button>
            <p className="my-3">30-DAY MONEY-BACK GUARANTEE</p>
            <img
              src="https://ftr.imgix.net/3EOOAeQsNMQBJkX2HPZqJn/7b4c25bcca074a531f74bbda530f87df/homepage-pingzhu-hero-figures-v2-opt__1___3_.png?auto=format%2Ccompress&cs=srgb&fit=max&q=60&w=720&s=016eb14da2e70c8bc93b13a566764d26"
              className="headingImg"
            />
          </div>
          <img
            src="https://ftr.imgix.net/FQBOc9Uh5e22pHikmfCJR/3ce3022343c7ad918545a6a2e01f36b5/homepage-pingzhu-hero-bg-opt-v2.jpg?auto=format%2Ccompress&cs=srgb&fit=max&q=60&w=1920&s=ae7331908c13b70917d2f5b72adea99b"
            className="w-100"
          />
        </div>
      </div>
      <div className="container-fluid px-0">
        <div className="row">
          <div className="col-lg-6 col-md-12 text-center mt-5">
            <img
              src="https://ftr.imgix.net/11AcQtchrMiZrKGz4ZRirN/7e44386a57d14027cc0924743d9567c4/brickwall-peek-through-with-cursor-opt.png?auto=format%2Ccompress&cs=srgb&fit=max&q=60&w=720&s=db20117586efc3781d59637d02d25e6b"
              className="img-fluid w-50"
            />
          </div>
          <div className="col-lg-6 col-md-12 mt-5 pt-5">
            <h3 className="mb-5">
              Secure Access, <br /> worldwide
            </h3>
            <p className="mb-5">
              Connect reliably from anywhere, to anywhere. <br /> Our network of
              high-speed servers across 94 countries puts you in control.
            </p>
            <button className="btn btn-success rounded-pill py-3 w-25 fw-bold text-white align-self-center">
              Get ExpressVPN
            </button>
          </div>
        </div>
      </div>
      <div className="container-fluid px-0">
        <div className="row">
          <div className="col-lg-6 col-md-12 mt-5 pt-5">
            <h3 className="mb-5 mx-5 px-5">
              Just one click to <br /> a safer internet{" "}
            </h3>
            <p className="mb-5 mx-5 px-5">
              Going online doesn’t have to mean being exposed. <br /> Whether
              you’re shopping from your desk or just connecting at a cafe,
              <br /> keep your personal information more private and secure.
            </p>
          </div>
          <div className="col-lg-6 col-md-12 text-center">
            <img
              src="https://ftr.imgix.net/2FqWXTKJh6g8PxBeOWwL1s/3a171e98ef364e47b22d0b90ef259478/unexposed-internet-lamp-opt.png?auto=format%2Ccompress&cs=srgb&fit=max&q=60&w=720&s=3c0d1ff289a55e693e2d29506993c13b"
              className="img-fluid w-50"
            />
          </div>
        </div>
      </div>
      <div className="container-fluid px-0">
        <div className="row">
          <div className="col-lg-6 col-md-12 text-center mt-5">
            <img
              src="https://ftr.imgix.net/4Hq0c6NKQtQpx4YOqPQCSB/d83bf26253974e69bdbeeed208d912ac/extend-your-coverage-with-a-vpn.png?auto=format%2Ccompress&cs=srgb&fit=max&q=60&w=720&s=851aad461e18fd68578b30d729d1be01"
              className="img-fluid w-50"
            />
          </div>
          <div className="col-lg-6 col-md-12 mt-5 pt-5">
            <h1 className="mb-5">
              Use ExpressVPN <br />
              on every device
            </h1>
            <p className="mb-5">
              Phone, tablet, computer, router—no matter where you are or what
              devices you’re using, a single ExpressVPN subscription has got you
              covered..
            </p>
            <div className="richtext-custom linked-images-wrapper d-flex justify-content-evenly mb-3">
              <div className="richtext-custom linked-image mx-2">
                <a href="/vpn-software/vpn-windows" target="_self" rel="">
                  <img
                    src="//images.ctfassets.net/u6u9ehxmteql/47HvG4QYSliQNfni1TGUNM/e850e56128f956dacf6cb1e00161adbf/windows-logo.svg"
                    alt="windows-icon"
                  />
                </a>
              </div>
              <div className="richtext-custom linked-image mx-2">
                <a href="/vpn-software/vpn-mac" target="_self" rel="">
                  <img
                    src="//images.ctfassets.net/u6u9ehxmteql/15zuyQR2s7nvN9N8GkdPRX/97d069f0366ed46b3f949be4bb2e4822/apple-logo.svg"
                    alt="apple-icon"
                  />
                </a>
              </div>
              <div className="richtext-custom linked-image mx-2">
                <a href="/vpn-software/vpn-android" target="_self" rel="">
                  <img
                    src="//images.ctfassets.net/u6u9ehxmteql/5GEKBnNE2F7tcvtDJecnJk/ae8226d02e75ae2aefee81769fa40ce7/android-logo.svg"
                    alt="android-icon"
                  />
                </a>
              </div>
              <div className="richtext-custom linked-image mx-2">
                <a href="/vpn-software/vpn-ios" target="_self" rel="">
                  <img
                    src="//images.ctfassets.net/u6u9ehxmteql/5aw7AoUSofVVVUrt4oGmZh/fa3fe639eac4049cf52840cfa05a4a72/ios-logo.svg"
                    alt="ios-icon"
                  />
                </a>
              </div>
              <div className="richtext-custom linked-image mx-2">
                <a href="/vpn-software/vpn-linux" target="_self" rel="">
                  <img
                    src="//images.ctfassets.net/u6u9ehxmteql/5wrRvLy05T6IXL11I3TSdH/6aacd544961a7b9e2632a640ce008d20/linux-logo.svg"
                    alt="linux-icon"
                  />
                </a>
              </div>
              <div className="richtext-custom linked-image">
                <a href="/vpn-software/vpn-router" target="_self" rel="">
                  <img
                    src="//images.ctfassets.net/u6u9ehxmteql/1tmtFH0eSbO81T1n7GEwVj/9ba90274e3135772b6ef0d33ef849091/router-icon.svg"
                    alt="Router-icon"
                  />
                </a>
              </div>
            </div>
            <button className="btn btn-success rounded-pill py-3 w-25 fw-bold text-white align-self-center">
              Get ExpressVPN
            </button>
          </div>
        </div>
      </div>
      <div className="container-fluid px-0 mt-5">
        <div className="row py-5">
          <div className="col-lg-4">
            <div className="card border-0">
              <img
                src="https://ftr.imgix.net/uoPgq1HAqZRS3jE7tdH0t/b4a797aa617cc7cbc03545217687fad9/blazing-fast-speeds.png?auto=format%2Ccompress&cs=srgb&fit=max&q=60&w=720&s=3769fd7122b6b19da2e9746f14168e72"
                className="card-img-top"
                alt="..."
              />
              <div className="card-body text-center">
                <h5 className="card-title">Stronger data protection</h5>
                <p className="card-text">
                  Take charge of your online privacy and security with
                  best-in-class encryption.
                </p>
              </div>
            </div>
          </div>
          <div className="col-lg-4 border-0">
            <div className="card border-0">
              <img
                src="https://ftr.imgix.net/5F2ySeLBognoZIJQNjyAot/71dd6fe83c1cc08ffa2dacde0759e39e/be-anywhere.png?auto=format%2Ccompress&cs=srgb&fit=max&q=60&w=720&s=3f84a447b3fc990628ec0e11e89e641f"
                className="card-img-top"
                alt="..."
              />
              <div className="card-body text-center">
                <h5 className="card-title">Works seamlessly everywhere</h5>
                <p className="card-text">
                  Experience the internet the way it’s meant to be. On the go,
                  or on your couch.
                </p>
              </div>
            </div>
          </div>
          <div className="col-lg-4 ">
            <div className="card border-0">
              <img
                src="https://ftr.imgix.net/6okBylTKqGv0FRM9yHPXs1/4a466e256a43ce031b3e0ebb0a1dbe28/serious-security.png?auto=format%2Ccompress&cs=srgb&fit=max&q=60&w=720&s=bfb3248b665ab05391c3ed97a5d26f4d"
                className="card-img-top"
                alt="..."
              />
              <div className="card-body text-center">
                <h5 className="card-title">Lightning-quick connectivity</h5>
                <p className="card-text">
                  Our VPN network is built for speed, powered by next-generation
                  technology.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="container-fluid">
        <div className="row">
          <img
            src="https://cdn.shopify.com/s/files/1/0653/0878/6936/files/Screenshot_2022-10-21_205846.png?v=1666366181"
            className="img-fluid w-100"
          />
        </div>
      </div>
      <footer className="footer container-fluid mx-0">
        <div className="cus_container justify-content-center">
          <div className="d-flex list-style-none text-decoration-none text-white">
            <ul className="footer-menu-col">
              <li className="footer-menu-title">Products</li>
              <li>
                <a className="text-decoration-none text-white" href="/aircove">Aircove</a>
              </li>
              <li>
                <a href="/vpn-software/vpn-mac" className="text-decoration-none text-white">Mac VPN</a>
              </li>
              <li>
                <a href="/vpn-software/vpn-windows" className="text-decoration-none text-white">VPN for PC</a>
              </li>
              <li>
                <a href="/vpn-software/vpn-ios"  className="text-decoration-none text-white">iPhone VPN</a>
              </li>
              <li>
                <a href="/vpn-software/vpn-android" className="text-decoration-none text-white">Android VPN</a>
              </li>
              <li>
                <a href="/vpn-software/vpn-linux" className="text-decoration-none text-white">Linux VPN</a>
              </li>
              <li>
                <a href="/vpn-software/vpn-router" className="text-decoration-none text-white">Router VPN</a>
              </li>
              <li>
                <a href="/vpn-software/chrome-vpn" className="text-decoration-none text-white">VPN Chrome Extension</a>
              </li>
              <li>
                <a href="/vpn-software/firefox-vpn" className="text-decoration-none text-white">VPN Firefox Extension</a>
              </li>
              <li>
                <a href="/vpn-software/edge-vpn" className="text-decoration-none text-white">VPN Edge Extension</a>
              </li>
              <li>
                <a href="/vpn-server" className="text-decoration-none text-white">VPN Server Locations</a>
              </li>
              <li>
                <a href="/lightway" className="text-decoration-none text-white">Lightway VPN Protocol</a>
              </li>
              <li>
                <a href="/order" className="text-decoration-none text-white">Buy VPN</a>
              </li>
              <li>
                <a href="/black-friday-cyber-monday" className="text-decoration-none text-white">Black Friday VPN</a>
              </li>
            </ul>
            <ul className="footer-menu-col">
              <li className="footer-menu-title" className="text-decoration-none text-white">Learn More</li>
              <li>
                <a href="/what-is-vpn" className="text-decoration-none text-white">What Is a VPN?</a>
              </li>
              <li>
                <a href="/get-started" className="text-decoration-none text-white">Top 5 VPN Uses</a>
              </li>
              <li>
                <a href="/blog/category/tips-tricks/" className="text-decoration-none text-white">How-To Privacy Guides</a>
              </li>
              <li>
                <a href="/blog/" className="text-decoration-none text-white">Blog</a>
              </li>
              <li>
                <a href="/digital-security-lab" className="text-decoration-none text-white">Digital Security Lab</a>
              </li>
            </ul>
            <ul className="footer-menu-col">
              <li className="footer-menu-title">Tools</li>
              <li>
                <a href="/what-is-my-ip" className="text-decoration-none text-white">What Is My IP?</a>
              </li>
              <li>
                <a href="/dns-leak-test" className="text-decoration-none text-white">DNS Leak Test</a>
              </li>
              <li>
                <a href="/webrtc-leak-test" className="text-decoration-none text-white">WebRTC Leak Test</a>
              </li>
              <li>
                <a href="/password-generator" className="text-decoration-none text-white">Password Generator</a>
              </li>
              <li>
                <a href="/blog/log4shell-protection/" className="text-decoration-none text-white">
                  Log4j Vulnerability (VPN Protection)
                </a>
              </li>
            </ul>
            <ul className="footer-menu-col">
              <li className="footer-menu-title">About ExpressVPN</li>
              <li>
                <a href="/about-us" className="text-decoration-none text-white">About Us</a>
              </li>
              <li>
                <a href="/order" className="text-decoration-none text-white">Plans and Pricing</a>
              </li>
              <li>
                <a href="/features" className="text-decoration-none text-white">Features</a>
              </li>
              <li>
                <a href="/features/vpn-trial" className="text-decoration-none text-white">Risk-Free VPN Trial</a>
              </li>
              <li>
                <a href="/reviews" className="text-decoration-none text-white">ExpressVPN Reviews</a>
              </li>
              <li>
                <a href="/press" className="text-decoration-none text-white">Press</a>
              </li>
              <li>
                <a href="/jobs" className="text-decoration-none text-white">Careers</a>
              </li>
              <li>
                <a href="/privacy-policy" className="text-decoration-none text-white">Privacy Policy</a>
              </li>
              <li>
                <a href="/trust" className="text-decoration-none text-white">Trust</a>
              </li>
            </ul>
            <ul className="footer-menu-col">
              <li className="footer-menu-title">Programs</li>
              <li>
                <a href="/refer-a-friend" className="text-decoration-none text-white">Refer a Friend</a>
              </li>
              <li>
                <a href="/affiliates" className="text-decoration-none text-white">Affiliates</a>
              </li>
              <li>
                <a href="/influencers" className="text-decoration-none text-white">Influencers</a>
              </li>
              <li>
                <a href="/partners" className="text-decoration-none text-white">Partners</a>
              </li>
              <li>
                <a href="/expressvpn-scholarship" className="text-decoration-none text-white">$5,000 Scholarship</a>
              </li>
            </ul>
            <ul className="footer-menu-col">
              <li className="footer-menu-title">Help</li>
              <li>
                <a href="/support/" className="text-decoration-none text-white">Support Center</a>
              </li>
              <li>
                <a href="/support/vpn-setup/" className="text-decoration-none text-white">VPN Setup Tutorials</a>
              </li>
              <li>
                <a href="/support/troubleshooting/frequently-asked-questions/" className="text-decoration-none text-white">
                  FAQ
                </a>
              </li>
              <li>
                <a href="/tos" className="text-decoration-none text-white">Terms of Service</a>
              </li>
              <li>
                <a href="#seopenchat" className="text-decoration-none text-white">Contact Us</a>
              </li>
              <li className="footer-dropdown">
                <span className="language-container">
                  <a
                    href="#"
                    onclick="event.preventDefault()"
                    className="text-decoration-none text-white"
                    aria-label="Language"
                  >
                    English
                  </a>
                  <div className="menu popup-menu">
                    <div className="menu-group menu-group-lang">
                      <ul className="menu-group-list">
                        <li>
                          <a href="/dk" className="text-decoration-none text-white">
                            Dansk
                          </a>
                        </li>
                        <li>
                          <a href="/de" className="text-decoration-none text-white">
                            Deutsch
                          </a>
                        </li>
                        <li>
                          <a href="/es" className="text-decoration-none text-white">
                            Español
                          </a>
                        </li>
                        <li>
                          <a href="/fr" className="text-decoration-none text-white">
                            Français
                          </a>
                        </li>
                        <li>
                          <a href="/it" className="text-decoration-none text-white">
                            Italiano
                          </a>
                        </li>
                        <li>
                          <a href="/nl" className="text-decoration-none text-white">
                            Nederlands
                          </a>
                        </li>
                        <li>
                          <a href="/no" className="text-decoration-none text-white">
                            Norsk
                          </a>
                        </li>
                        <li>
                          <a href="/pl" className="text-decoration-none text-white">
                            Polski
                          </a>
                        </li>
                        <li>
                          <a href="/pt" className="text-decoration-none text-white">
                            Português
                          </a>
                        </li>
                        <li>
                          <a href="/fi" className="text-decoration-none text-white">
                            Suomi
                          </a>
                        </li>
                        <li>
                          <a href="/se" className="text-decoration-none text-white">
                            Svenska
                          </a>
                        </li>
                        <li>
                          <a href="/tr" className="text-decoration-none text-white">
                            Türkçe
                          </a>
                        </li>
                        <li>
                          <a href="/ru" className="text-decoration-none text-white">
                            Русский
                          </a>
                        </li>
                        <li>
                          <a href="/th" className="text-decoration-none text-white">
                            ภาษาไทย
                          </a>
                        </li>
                        <li>
                          <a href="/jp" className="text-decoration-none text-white">
                            日本語
                          </a>
                        </li>
                        <li>
                          <a href="/kr" className="text-decoration-none text-white">
                            한국어
                          </a>
                        </li>
                        <li>
                          <a href="/ar" className="text-decoration-none text-white">
                            اَلْعَرَبِيَّةُ
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </span>
              </li>
            </ul>
          </div>
        </div>
        <div className="footer-bottom">
          <div className="d-flex align-items-center justify-content-evenly h-10">
            <p className="caption text-white mt-4">© 2022 ExpressVPN. All rights reserved.</p>
            <div className="footer-bottom-social d-flex justify-content-between">
              <a
                href="https://www.youtube.com/user/expressvpn"
                className="footer-icon-youtube mx-2"
                target="_blank"
                rel="noopener noreferrer"
              >
                <span className="sr-only">Youtube</span>
              </a>
              <a
                href="https://www.linkedin.com/company/expressvpn/life/life-at-expressvpn"
                className="footer-icon-linkedin mx-2"
                target="_blank"
                rel="noopener noreferrer"
              >
                <span className="sr-only">Linkedin</span>
              </a>
              <a
                href="https://twitter.com/expressvpn"
                className="footer-icon-twitter mx-2"
                target="_blank"
                rel="noopener noreferrer"
              >
                <span className="sr-only">Twitter</span>
              </a>
              <a
                href="https://www.facebook.com/ExpressVPN/"
                className="footer-icon-facebook mx-2"
                target="_blank"
                rel="noopener noreferrer"
              >
                <span className="sr-only">Facebook</span>
              </a>
              <a
                href="https://www.instagram.com/expressvpn/"
                className="footer-icon-instagram"
                target="_blank"
                rel="noopener noreferrer"
              >
                <span className="sr-only">Instagram</span>
              </a>
            </div>
          </div>
        </div>
      </footer>
    </>
  );
}
